CREATE DATABASE `final_project`;
USE final_project;

DROP TABLE IF EXISTS `people`;
CREATE TABLE people (
  `personid` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `firstname` VARCHAR(255) NOT NULL DEFAULT '',
  `lastname` VARCHAR(255) NOT NULL DEFAULT '' ,
  `email` VARCHAR(255) NOT NULL DEFAULT '' 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `items`;
CREATE TABLE items (
  `itemid` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `orders`;
CREATE TABLE orders (
  `orderid` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `personid` INT UNSIGNED NOT NULL,
  `orderdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (personid) REFERENCES people (personid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `order_details`;
CREATE TABLE order_details (
  `orderdetailsid` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `orderid` INT UNSIGNED NOT NULL,
  `itemid` INT UNSIGNED NOT NULL,
  `quantity` INT,
  FOREIGN KEY (orderid) REFERENCES orders (orderid),
  FOREIGN KEY (itemid) REFERENCES items (itemid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

